# Generated by Django 5.2.7 on 2025-12-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=500)),
                ('Phone', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('BusinessName', models.CharField(blank=True, max_length=100, null=True)),
                ('IDImage', models.ImageField(upload_to='documents/')),
                ('LivePhoto', models.ImageField(upload_to='live_photos/')),
            ],
        ),
        migrations.RenameModel(
            old_name='SignUp',
            new_name='SignUpBuyer',
        ),
    ]
