# Generated by Django 5.2.7 on 2025-12-26 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0002_signupseller_rename_signup_signupbuyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupseller',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
