# Generated by Django 5.2.7 on 2025-12-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0003_signupseller_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='sneakers/')),
                ('end_time', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
    ]
