# Generated by Django 5.2.7 on 2025-12-27 10:21

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0004_sneaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneaker',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakpeek.signupbuyer')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='sneakpeek.sneaker')),
            ],
        ),
    ]
