# Generated by Django 5.2.7 on 2025-12-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0005_alter_sneaker_description_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.FloatField()),
                ('product_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
    ]
