# Generated by Django 5.2.7 on 2026-01-21 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakpeek', '0008_add_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='product_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='sneakpeek.productrequest'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='sneaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='sneakpeek.sneaker'),
        ),
    ]
